name: changes_from_realm
on:
  push:
    branches: 
      - 'main'
jobs:
   pack_realm_functions:
      if: github.actor == 'mongodb-realm[bot]'
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          name: Set up Node.js
        - name: Pack functions into sub-directories
          run: | 
            npm install mv
            cd node_scripts
            cd workflows
            node pack_realm_functions.js
        - name: Git Config
          env: 
            GITHUB_MESSAGE: ${{ github.event.head_commit.message }}
            GITHUB_ACTOR_EMAIL: ${{github.actor}}
            GITHUB_ACTOR_USER_NAME: ${{github.actor}}
          run: |
            git config pull.rebase false
            git config --local user.email "${GITHUB_ACTOR_EMAIL}@users.noreply.github.com"
            git config --local user.name "${GITHUB_ACTOR_USER_NAME}"
          
        - name: Git commit to production
          id: commit_files
          env: 
              GITHUB_MESSAGE: ${{ github.event.head_commit.message }}
          run: |
            git add .
            git commit -m "${GITHUB_MESSAGE}"
          continue-on-error: true

        - name: Git merge
          id: git_merge
          run: |
            git pull origin production --allow-unrelated-histories --strategy-option ours

        - name: Push workflow changes to repo
          uses: ad-m/github-push-action@master
          if: steps.git_merge.outcome == 'success'
          with:
            branch: production
            github_token: ${{ github.token }}


