name: copy_realm_functions
on:
  push:
    branches: 
      - "*" 
jobs:
   copy_realm_functions:
      runs-on: ubuntu-latest
      env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
      steps: 
        - uses: actions/checkout@v2
        - run: | 
            echo "$GITHUB_CONTEXT"
    
  
