name: pack_realm_functions
on:
  pull_request:
    branches: 
      - main 
jobs:
   pack_realm_functions:
      if: github.ref_name != 'main'
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          name: Set up Node.js
        - name: Pack functions into sub-directories
          run: | 
            npm install mv
            cd node_scripts
            cd workflows
            node pack_realm_functions.js
        - name: Commit files
          run: |
            git config --local user.email "test@github.com"
            git config --local user.name "GitHub Action test" 
            git add *
            git commit -m "pack realm functions"
        - name: Push workflow changes to repo
          uses: ad-m/github-push-action@master
          with:
            branch: ${{ github.ref }}
            github_token: ${{ github.token }}


