name: unpack_realm_functions
on:
  push:
    branches: 
      - main 
    paths: 
      - 'functions/**'
jobs:
   unpack_realm_functions:
      runs-on: ubuntu-latest
      if: github.actor != 'mongodb-realm[bot]'
      steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          name: Set up Node.js
          with:
              node-version: 16
        - name: Unpack functions into sub-directories
          run: | 
            npm install mv
            cd node_scripts
            cd workflows
            node unpack_realm_functions.js
        - name: Commit files
          env: 
            GITHUB_CONTEXT: ${{ github.event.head_commit.message }}
          run: |
            git config --local user.email "test@github.com"
            git config --local user.name "GitHub Action test" 
            git add .
            git commit -m "${GITHUB_CONTEXT}"
        - name: Push workflow changes to repo
          uses: ad-m/github-push-action@master
          with:
            branch: main
            github_token: ${{ github.token }}
