name: unpack_realm_functions
on:
  push:
    branches: 
      - staging 
      - main
    paths: 
      - 'directory_structures/functions/**'
      - 'functions/**'
  pull_request: 
    branches: 
      - staging 
    paths: 
      - 'directory_structures/functions/**'
      - 'functions/**'
jobs:
   unpack_realm_functions:
      runs-on: ubuntu-latest
      if: github.actor != 'mongodb-realm[bot]'
      steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          name: Set up Node.js
          with:
              node-version: 16
        - name: Unpack functions function directories
          run: | 
            npm install mv
            cd node_scripts
            cd workflows
            node unpack_realm_functions.js
        - name: Git Config
          env: 
            GITHUB_MESSAGE: ${{ github.event.head_commit.message }}
            GITHUB_ACTOR_EMAIL: ${{github.actor}}
            GITHUB_ACTOR_USER_NAME: ${{github.actor}}
          run: |
            git config pull.rebase false
            git config --local user.email "${GITHUB_ACTOR_EMAIL}@users.noreply.github.com"
            git config --local user.name "${GITHUB_ACTOR_USER_NAME}"
        - name: Git commit to main
          id: commit_files
          env: 
              GITHUB_MESSAGE: ${{ github.event.head_commit.message }}
          run: |
            git add .
            git commit -m "${GITHUB_MESSAGE}"
          continue-on-error: true
        - name: Git merge
           if: steps.commit_files.outcome == 'success'
           id: git_merge
           run: |
            git pull origin main --allow-unrelated-histories --strategy-option ours
        - name: Push workflow changes to repo
          uses: ad-m/github-push-action@master
          if: steps.git_merge.outcome == 'success'
          with:
            branch: main
            github_token: ${{ github.token }}